
name: Coverage Report

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    name: Report test coverage
    runs-on: ubuntu-latest
    environment: codacy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run coverage-ci
      env:
        TEST: ${{ secrets.TEST }}
    - run: echo let me $TEST
    - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --project-token $CODACY_PROJECT_TOKEN -r coverage/lcov.info
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
